#!/opt/anaconda3/bin/python3

import pandas as pd
import sys

place, lat, lon = sys.argv[1:]

from boats import F_DESTINATIONS

df = pd.read_csv(F_DESTINATIONS)


if place not in list(df['Name']):
    newrow = pd.DataFrame({'Name': [place], 'Lat': [lat], 'Lon': [lon]})
    df.to_csv(F_DESTINATIONS, index=False)
    print(pd.read_csv(F_DESTINATIONS).tail(1))
else:
    print('Already exists!')
    print(df[df['Name'] == place])
