#!/opt/anaconda3/bin/python3
import sys
from keras import models
import pandas as pd

import warnings

warnings.filterwarnings("ignore", category=UserWarning)

modelfile = 'predspd.keras'

tws = float(sys.argv[1])
twd = int(sys.argv[2])
hdg = int(sys.argv[3])

print(f'tws: {tws}\ntwd: {twd}\nhdg: {hdg}')

m = models.load_model(modelfile)

predictors = pd.DataFrame([[tws, twd, hdg]])
spd = round(m.predict(predictors)[0][0],1)

print(spd)
